In [67]:
import pandas as pd

In [68]:
df = pd.read_csv("nba_games_runtime.csv", index_col=0)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22039,240.0,240.0,44.0,83.0,0.530,13.0,26.0,0.500,12.0,19.0,...,40.0,34.5,170.0,121.0,MIL,110,0,2024,2024-02-15,True
22040,240.0,240.0,46.0,89.0,0.517,11.0,30.0,0.367,25.0,27.0,...,25.8,31.5,200.0,137.0,POR,91,1,2024,2024-02-15,True
22041,240.0,240.0,31.0,83.0,0.373,8.0,29.0,0.276,21.0,30.0,...,33.3,33.0,181.0,101.0,MIN,128,0,2024,2024-02-15,False
22042,240.0,240.0,49.0,92.0,0.533,20.0,42.0,0.476,22.0,28.0,...,66.7,30.8,175.0,146.0,UTA,137,1,2024,2024-02-15,True
22043,240.0,240.0,43.0,93.0,0.462,22.0,49.0,0.449,29.0,32.0,...,25.0,33.4,189.0,142.0,GSW,140,0,2024,2024-02-15,False

In [69]:
# Remove extraneous columns
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

phrase = "_opp"
remove = [l for l in df.columns if phrase in l]
df_cleaned = df.drop(columns=remove)
df_cleaned.head()
df = df_cleaned
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,season,date,won
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,True
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,False
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,False
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,True
4,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22039,240.0,44.0,83.0,0.530,13.0,26.0,0.500,12.0,19.0,0.632,...,25.0,32.0,161.0,118.0,MEM,113,1,2024,2024-02-15,True
22040,240.0,46.0,89.0,0.517,11.0,30.0,0.367,25.0,27.0,0.926,...,33.3,33.0,181.0,101.0,MIN,128,0,2024,2024-02-15,True
22041,240.0,31.0,83.0,0.373,8.0,29.0,0.276,21.0,30.0,0.700,...,25.8,31.5,200.0,137.0,POR,91,1,2024,2024-02-15,False
22042,240.0,49.0,92.0,0.533,20.0,42.0,0.476,22.0,28.0,0.786,...,25.0,33.4,189.0,142.0,GSW,140,0,2024,2024-02-15,True
22043,240.0,43.0,93.0,0.462,22.0,49.0,0.449,29.0,32.0,0.906,...,66.7,30.8,175.0,146.0,UTA,137,1,2024,2024-02-15,False

In [70]:
df = df.sort_values(by=['team', 'date'])
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,season,date,won
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,False
38,240.0,42.0,83.0,0.506,10.0,24.0,0.417,18.0,26.0,0.692,...,22.5,33.6,155.0,111.0,ATL,112,0,2016,2015-10-29,True
41,240.0,36.0,83.0,0.434,8.0,23.0,0.348,17.0,22.0,0.773,...,23.4,26.3,123.0,105.0,ATL,97,1,2016,2015-10-30,True
80,240.0,37.0,88.0,0.420,7.0,29.0,0.241,13.0,14.0,0.929,...,37.5,26.6,142.0,110.0,ATL,94,0,2016,2015-11-01,True
112,240.0,37.0,90.0,0.411,7.0,21.0,0.333,17.0,22.0,0.773,...,36.8,29.3,135.0,105.0,ATL,98,0,2016,2015-11-03,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21923,240.0,42.0,94.0,0.447,16.0,40.0,0.400,6.0,9.0,0.667,...,42.4,36.3,247.0,119.0,WAS,106,1,2024,2024-02-07,False
21942,240.0,45.0,95.0,0.474,20.0,47.0,0.426,19.0,21.0,0.905,...,33.3,28.2,155.0,130.0,WAS,129,0,2024,2024-02-09,False
21975,240.0,42.0,86.0,0.488,13.0,35.0,0.371,16.0,21.0,0.762,...,25.2,25.9,164.0,123.0,WAS,113,1,2024,2024-02-10,False
21986,240.0,44.0,106.0,0.415,7.0,32.0,0.219,9.0,15.0,0.600,...,20.3,29.5,138.0,107.0,WAS,104,0,2024,2024-02-12,False
22026,240.0,44.0,92.0,0.478,21.0,45.0,0.467,17.0,20.0,0.850,...,50.0,32.9,180.0,137.0,WAS,126,0,2024,2024-02-14,False

In [71]:
def average_stats_last_10_games(group):
    last10 = group.tail(10)
    averages = last10.mean(numeric_only=True)
    return averages

In [72]:
avg_stats_by_team = df.groupby('team').apply(average_stats_last_10_games)
avg_stats_by_team

C:\Users\Bryan Hernandez\AppData\Local\Temp\ipykernel_32388\578366165.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  avg_stats_by_team = df.groupby('team').apply(average_stats_last_10_games)

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,total,home,season,won
team,,,,,,,,,,,,,,,,,,,,,
ATL,242.5,45.7,95.4,0.4791,13.9,39.0,0.3533,21.6,26.4,0.8258,...,3.79,7.13,31.44,32.28,217.1,130.7,126.9,0.7,2024.0,0.6
BOS,240.0,44.8,90.8,0.4958,16.0,42.5,0.3773,14.5,17.4,0.8448,...,4.04,9.73,28.31,32.58,202.4,120.4,120.1,0.8,2024.0,0.8
BRK,240.0,41.7,88.8,0.4687,14.6,36.7,0.3974,14.8,19.5,0.7834,...,5.42,10.22,49.41,32.37,187.3,129.5,112.8,0.8,2024.0,0.4
CHI,245.0,43.4,87.7,0.4961,11.6,31.8,0.3695,18.7,23.1,0.8053,...,6.54,8.94,37.86,29.05,159.1,127.3,117.1,0.3,2024.0,0.5
CHO,240.0,40.6,86.9,0.4670,12.6,34.0,0.3692,13.6,17.6,0.7584,...,4.84,6.90,41.12,35.79,190.8,125.6,107.4,0.8,2024.0,0.3
CLE,240.0,44.5,88.1,0.5056,14.1,38.2,0.3688,15.6,19.5,0.7983,...,4.04,11.89,33.44,33.29,183.9,118.9,118.7,0.5,2024.0,0.9
DAL,240.0,43.3,86.3,0.5039,14.0,37.3,0.3724,17.7,23.8,0.7359,...,5.46,8.59,47.74,35.78,185.9,121.1,118.3,0.6,2024.0,0.7
DEN,240.0,39.6,88.9,0.4455,10.5,30.9,0.3336,15.6,20.1,0.7965,...,11.49,9.91,29.63,36.58,186.6,124.4,105.3,0.5,2024.0,0.5
DET,242.5,43.0,91.6,0.4728,12.1,31.3,0.3900,16.6,21.0,0.8081,...,4.70,7.47,34.97,29.02,211.9,125.8,114.7,0.4,2024.0,0.3
GSW,242.5,47.1,95.0,0.4993,15.5,38.3,0.4001,15.1,19.3,0.7699,...,7.35,12.44,38.03,37.03,189.2,119.3,124.8,0.3,2024.0,0.8
HOU,240.0,42.0,92.4,0.4534,11.7,34.6,0.3454,17.0,22.8,0.7586,...,7.05,7.74,37.89,31.95,186.3,121.3,112.7,0.4,2024.0,0.3
IND,240.0,45.9,89.7,0.5144,12.5,33.2,0.3772,13.4,18.5,0.7211,...,4.48,7.00,36.93,30.57,186.9,127.0,117.7,0.4,2024.0,0.5
LAC,240.0,42.0,86.9,0.4826,13.1,34.4,0.3838,21.3,25.5,0.8404,...,5.04,7.52,44.50,34.82,194.5,125.7,118.4,0.3,2024.0,0.7
LAL,245.0,45.4,89.7,0.5068,12.3,31.8,0.3842,21.4,27.4,0.7721,...,6.27,9.85,31.26,38.15,191.2,126.4,124.5,0.3,2024.0,0.7
MEM,240.0,38.0,85.5,0.4454,14.5,39.0,0.3795,13.2,18.6,0.7103,...,5.00,8.45,26.51,34.87,157.9,124.3,103.7,0.7,2024.0,0.2
MIA,240.0,40.9,88.1,0.4649,12.3,35.1,0.3490,16.8,20.0,0.8489,...,5.08,4.65,35.91,37.28,180.9,117.5,110.9,0.6,2024.0,0.6
MIL,240.0,41.1,87.0,0.4726,14.1,39.8,0.3604,14.7,20.7,0.7209,...,5.82,7.03,49.03,40.30,198.4,124.0,111.0,0.4,2024.0,0.3
MIN,242.5,42.9,85.2,0.5047,14.0,33.6,0.4178,18.1,22.9,0.7877,...,8.78,7.93,35.29,40.53,194.6,117.5,117.9,0.3,2024.0,0.7
NOP,240.0,43.7,87.7,0.4967,11.2,31.8,0.3500,16.6,21.5,0.7756,...,9.56,7.66,48.08,38.92,180.4,121.2,115.2,0.2,2024.0,0.7
NYK,240.0,42.2,90.8,0.4672,11.8,33.8,0.3528,15.3,19.0,0.8073,...,4.90,12.06,50.99,42.47,179.1,126.5,111.5,0.7,2024.0,0.5
OKC,245.0,42.7,88.8,0.4838,14.5,36.4,0.4012,16.1,19.8,0.8203,...,8.28,10.37,47.30,35.24,208.5,124.7,116.0,0.5,2024.0,0.6
ORL,242.5,42.5,85.2,0.5014,11.8,30.6,0.3914,16.8,22.1,0.7652,...,5.83,12.21,52.80,34.65,227.4,123.6,113.6,0.5,2024.0,0.7
PHI,240.0,42.7,92.1,0.4642,10.4,31.4,0.3321,17.4,21.8,0.8041,...,5.18,10.06,37.57,35.17,169.8,133.8,113.2,0.5,2024.0,0.3
PHO,240.0,45.5,85.3,0.5346,11.3,29.7,0.3789,19.0,24.9,0.7609,...,5.71,10.00,39.29,42.68,210.2,121.7,121.3,0.4,2024.0,0.7
POR,242.5,38.5,84.5,0.4546,9.7,29.4,0.3330,19.5,23.6,0.8349,...,5.28,7.11,45.66,35.93,184.5,128.7,106.2,0.7,2024.0,0.2
SAC,240.0,44.8,90.0,0.4985,13.4,37.9,0.3527,14.0,19.3,0.7123,...,6.65,5.37,42.52,34.05,191.6,125.1,117.0,0.2,2024.0,0.5
SAS,240.0,40.8,89.9,0.4571,11.1,34.6,0.3258,14.4,18.8,0.7584,...,5.89,9.65,31.75,33.68,167.6,124.8,107.1,0.5,2024.0,0.2
TOR,245.0,41.9,90.7,0.4632,11.4,31.3,0.3620,17.3,21.6,0.7970,...,5.88,8.99,49.29,27.49,168.7,130.5,112.5,0.4,2024.0,0.3
UTA,240.0,43.8,91.0,0.4811,14.0,38.0,0.3647,18.7,22.9,0.8164,...,6.22,16.60,45.70,36.97,199.9,136.5,120.3,0.6,2024.0,0.3
WAS,240.0,43.7,94.2,0.4652,12.4,36.1,0.3358,13.9,18.4,0.7426,...,6.58,8.29,37.95,31.70,181.4,124.7,113.7,0.5,2024.0,0.2